name: customerapp
description: Products and Services management app.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.3.0+16

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_facebook_login: ^3.0.0
  http: ^0.12.2
  google_sign_in: ^4.5.5
  shared_preferences: ^0.5.12+4
  mailer: ^3.2.1
  get: ^3.17.1
  image_picker: ^0.6.7+21
  palette_generator: ^0.2.3
  image_cropper: ^1.3.1
  carousel_slider: ^2.3.1
  url_launcher: ^5.7.10
  intl: ^0.16.1
  provider: ^4.3.2+3
  geolocator: ^6.1.14
  geocoder: ^0.2.1
  fluttertoast: ^7.1.6
  flutter_webview_plugin: ^0.3.11
  intl_phone_number_input: ^0.6.0
  package_info: ">=0.4.3+4 <2.0.0"
  flutter_barcode_scanner: ^1.0.1
  filesystem_picker: ^1.0.3
  path_provider: ^1.6.28
  # gx_file_picker: ^1.9.0+2
  file_picker: ^2.1.7

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  photo_view: ^0.10.3
  sign_in_with_apple: ^3.0.0
  apple_sign_in: ^0.1.0
  firebase_auth: ^0.20.1
  cloud_firestore: ^0.16.0+1
  firebase: ^8.0.0
  firebase_core: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2
  change_app_package_name: ^0.1.2
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
 
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/icons/flags/
    - assets/images/
    - assets/icons/fileIcons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
